### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by ethamitc** [LeonardSSH/vscord#5] opened 2021-03-01 15:09 UTC
Their appears to be a minor memory leak.
![image](https://user-images.githubusercontent.com/27776796/109516465-3a6ec680-7a76-11eb-8168-1995a685bf06.png)

After disabling & reloading:
![image](https://user-images.githubusercontent.com/27776796/109516492-40fd3e00-7a76-11eb-8055-bd6ac0c10716.png)

**Comment by LeonardSSH** [comment] 2021-03-01 22:45
Are you sure about this? I've never had this problem before. 🤔🤔

**Comment by ethamitc** [comment] 2021-03-02 15:12
> Are you sure about this? I've never had this problem before. 🤔🤔

Positive. It resolved itself after uninstalling the extension & reloading vscode. Hours later still no issue.

**Comment by LeonardSSH** [comment] 2021-03-02 16:45
Hmm, ok, very weird, I'll take a look to see what I did wrong. 👍

**Comment by ethamitc** [comment] 2021-03-04 03:24
cheers.

**Comment by LeonardSSH** [comment] 2021-08-10 01:23
The problem should be fixed in the newly released version, please upgrade to the extension and let me know if the problem is fixed.

**Comment by LeonardSSH** [comment] 2021-08-10 19:40
https://github.com/LeonardSSH/vscord/issues/7#issuecomment-896199539

**Closed by LeonardSSH** 2021-08-10 19:40 UTC
