### ISSUE TITLE
Always reporting Idling

### ISSUE THREAD

**Issue by AtherActive** [LeonardSSH/vscord#9] opened 2021-04-18 14:22 UTC
When I did a check on what the extension is showing on Discord, it always says "Idling", no matter what I do.

I am working with Python in a folder that also is a git repo.

**Comment by LeonardSSH** [comment] 2021-08-10 01:23
The problem should be fixed in the newly released version, please upgrade to the extension and let me know if the problem is fixed.

**Closed** 2021-08-15 12:28 UTC
